version: '3.8'

services:
  simplewebapp:
    image: 'simplewebapp'
    build:
      context: .
    container_name: simplewebapp
    ports:
      - 8080:8080
    depends_on:
      - db
      - activemq
    restart: always
    environment:
      - POSTGRES_HOST=db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employeedb
      - 'active-mq.broker-url=tcp://activemq:61616'

  db:
    image: 'postgres:13'
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data/pgdata
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=employeedb
      - PGDATA=/var/lib/postgresql/data/pgdata

  activemq:
        image: "rmohr/activemq"
        container_name: activemq
        ports:
          - "8161:8161"